[package]
name = "war_of_the_dukes"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = { git = "https://github.com/GodotNativeTools/godot-rust"}
hex2d = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_scan = "0.3"
